stage:
    deploy:
        DATABASE_CONFIGURATION:
            _merge: false
            connection:
                default:
                    username: user
                    host: database.internal                                                                                       #
                    dbname: main
                    password: ''
                    engine: innodb
                    initStatements: 'SET NAMES utf8;'
                    active: 1
    global:
        MIN_LOGGING_LEVEL: debug